---
# See https://github.com/jvautier/project-cli
fullname: jvautier/vuepress-helpcenter-template
description: Template for help center documentation with vuepress
tags:
  - documentation
  - vue-press
  - template
github:
  has_issues: true
  has_projects: false
  has_wiki: false
